### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by fxedel** [Manabu-GT/DesignOverlay-Android#14]
This app is already open source, so what about submitting it to F-Droid, an app repository for FOSS Android apps?

**Comment by fxedel** [comment]
See here for more information about submitting apps to F-Droid: https://f-droid.org/contribute/

**Comment by Manabu-GT** [comment]
I've never heard of f-droid. I will take a look.

**Comment by fxedel** [comment]
Great! F-Droid is a fork of Aptoide. It's an app store that only publishes applications which are free and open source (FOSS). I really like it because I don't have Google Apps installed on my phone and downloading the apps from F-Droid is much more convenient and safer than searching for apks in the web.

**Comment by reggiehg** [comment]
Hello,

­I tried emailing you but got an email error message. I have some questions regarding your GooglePlay app DisplayOverlay, if you don't mind?

The top portion of yo­ur Google Play page, ­as shown by the attac­hed 1st screenshot, s­hows major lines & mi­nor lines (3 per majo­r line). I can't seem­ to enable the minor ­lines though, unless ­your app doesn't actu­ally have that featur­e?

Also, I can't figure ­out what the Design-E­nabled, Design-Alpha,­ & Grid-Enabled setti­ngs mean in the attac­hed 2nd screenshot?

Tia,­

Reggie Guevara

­--Sent from Mail.Ru app for Android-------- Forwarded Message --------From: Mail Delivery Subsystem MAILER-DAEMON@www2259.sakura.ne.jpTo: reggiehg.sites@gmail.comDate: Friday, 30 September 2016, 09:34PM +08:00Subject: Returned mail: see transcript for detailsThe original message was received at Fri, 30 Sep 2016 22:34:56 +0900 (JST)from fsav409.sakura.ne.jp [133.242.250.108]   ----- The following addresses had permanent fatal errors -----contact@ms-square.com    (reason: Insufficient permission)   ----- Transcript of session follows -----maildrop: maildir over quota.550 5.0.0 contact@ms-square.com... Insufficient permission

![tmp_12846-screenshot_20160930-211411909184844](https://cloud.githubusercontent.com/assets/22547110/18998548/b2e97360-876b-11e6-8eb0-64fb0f84b852.png)

![tmp_12846-screenshot_20160930-211903976891402](https://cloud.githubusercontent.com/assets/22547110/18998667/373ba2aa-876c-11e6-962f-c83e9fe00930.png)

**Comment by Manabu-GT** [comment]
Hi @reggiehg,

I apologize for my late response.

The top portion of yo­ur Google Play page, ­as shown by the attac­hed 1st screenshot, s­hows major lines & mi­nor lines (3 per majo­r line). I can't seem­ to enable the minor ­lines though, unless ­your app doesn't actu­ally have that featur­e?
->Sorry for confusion. The app does not support such feature. It is just how the app icon was designed.

Also, I can't figure ­out what the Design-E­nabled, Design-Alpha,­ & Grid-Enabled setti­ngs mean in the attac­hed 2nd screenshot?
-> Design-Enabled means it will overlay whichever image you pick in the design section. Design-Alpha means you can adjust the transparency of the image you chose. Lastly, Grid-Enabled allows you to control whether to show the grid lines as an overlay.

Thank you for using the app.
